### ISSUE TITLE
Overall settings page / manage elections page

### ISSUE THREAD

**Issue by justetz** [wtg/elections#37]
Needed features (known so far):
- Create, edit, and delete elections
- Set the currently active election
- Hide / show the entire website
- Edit the homepage content

**Comment by jzblee** [comment]
Just figured you can't assign multiple people... but I'd be happy to help with this

**Comment by jzblee** [comment]
The ability to select the currently active election was added in commit 9e67986ed049a2f628a2cdf502fa9c0ca38cb8b7.

**Comment by jzblee** [comment]
The ability to create, edit, and delete elections was added in commit 8cde196f1acaa85f001f2c8d5cb7caa6f048547c.

Some sub-issues that remain (with regards to this feature):
- An active election ID is still not automatically generated and set if it is null, leading to errors.
- The election form does not contain any validation.
- There is no functionality in place to handle the deletion of elections with offices associated to them.

**Comment by jzblee** [comment]
An option to show/hide the entire website (e.g. maintenance mode) was added in commit b494d0f416eae5503717a74c994cbb9b3e50ac4d; pending discussion.

**Comment by jzblee** [comment]
Election form validation added in commit fefc9cad071c9775be64cb1ca4d4968e1706cc41.
