### ISSUE TITLE
Preferred name not given preference in candidate card on offices page

### ISSUE THREAD

**Issue by justetz** [wtg/elections#41]
<img width="266" alt="screen shot 2016-02-28 at 4 45 24 pm" src="https://cloud.githubusercontent.com/assets/1284928/13382132/d302557a-de3a-11e5-84c3-9947b1829fd3.png">
<img width="568" alt="screen shot 2016-02-28 at 4 45 38 pm" src="https://cloud.githubusercontent.com/assets/1284928/13382133/d30ca62e-de3a-11e5-820e-99427cca86cd.png">

**Comment by justetz** [comment]
@jzblee can you look into this? The edit candidate page has code for preferred names taking preference over a first name.

**Comment by jzblee** [comment]
@justetz Apologies, I missed this.
