### ISSUE TITLE
Email and site notifications

### ISSUE THREAD

**Issue by justetz** [wtg/elections#54]
Create an automated, candidate-customizable notification system for candidates: either by email, visible on the site, or both.

Notifications could include:
- Nominations added
- Candidate assistant added
- New AMA question posted
- New contact (changing contact from a mailto link to a form)

**Comment by draab** [comment]
I now have the information needed to send authentication emails from rne@rpi.edu. Shoot me a text to get the password.

**Comment by draab** [comment]
I'll take this one on. It actually seems fairly easy to do (https://nodemailer.com/about/)

I'll just have it email at the end of the API call for adding the candidate itself to start with.

**Comment by kochman** [comment]
Thanks David! I'll review your PR whenever it's ready.

**Comment by kochman** [comment]
Resolved with 99c7944
