### ISSUE TITLE
Candidate view displays major even if not set

### ISSUE THREAD

**Issue by kochman** [wtg/elections#66]
If a candidate hasn't defined a major, it should be hidden under the "Candidate Facts" section. See screenshot.
![lapreblem](https://cloud.githubusercontent.com/assets/335234/18403364/4f906c7a-76b2-11e6-83df-ad810c7dbfdc.png)

**Comment by draab** [comment]
Why don't you pull major from the CMS API?

**Comment by kochman** [comment]
I spoke with Justin, and the reason Elections doesn't pull a candidate's major from CMS is that it only provides one even if a candidate has multiple. I think it would probably make sense to use it to populate the field by default for new candidates (and they can edit it if necessary), so I'll open an issue. Thanks for the idea!
