### ISSUE TITLE
Create Elections Mailing Lists

### ISSUE THREAD

**Issue by draab** [wtg/elections#70]
The Union is switching to sympa for mailing lists and sympa mailings can be powered from an external dat source.

However, it can't ingest JSON so it needs a just a plain text listing of email addresses. For example:

raabd@rpi.edu
poly@rpi.edu
random-candidate@rpi.edu

Finally, the only authentication sympa supports is HTTP Basic.

**Comment by kochman** [comment]
@draab What groupings are you looking for? E.g. A route for each office, plus a route with all candidates for everything?

**Comment by draab** [comment]
Yes a route for all candidates in the active election is essential and also each office would be nice to have. My goal is to be able to only enter candidates once as opposed to having to maintain 2 separate lists.

**Comment by jzblee** [comment]
I got it, somewhat. Let me know if the format is incorrect.

**Comment by draab** [comment]
It works! 

I just added the API to sympa and added myself to Independent Senator (and quickly removed myself) and it works with sympa.

Thanks.

**Comment by kochman** [comment]
Is it okay that it's outputting `<br\>` (HTML) after each address instead of just `\n` (plain text)? Not sure exactly what Sympa expects.

**Comment by jzblee** [comment]
I had considered that and went off what I saw in the browser. \n makes more sense, though.

**Comment by draab** [comment]
Sympa needs the new line (just tried inputting you and I and it doesn't work).

**Comment by jzblee** [comment]
Updated with newlines. How does it look now?

**Comment by kochman** [comment]
Looks great. Can you have it send a `Content-Type: text/plain` header? Just to be completely correct.

**Comment by draab** [comment]
yeah that's what CMS does for it's mailing list api. It does work now because it recognizes each email as being unique so I can go ahead and remove Sid and I for real now.

**Comment by jzblee** [comment]
Got it. Pushed and deploying now.

**Comment by kochman** [comment]
Awesome. Thanks guys. #WebTechGoesAgile
