### ISSUE TITLE
Strip all reference to Political Parties

### ISSUE THREAD

**Issue by draab** [wtg/elections#71]
They are not a thing in this year's elections

**Comment by justetz** [comment]
Might be worthwhile not deleting the code altogether, just making it a toggle so that it could be re-added in the future if needed.

**Comment by kochman** [comment]
I think a toggle in the admin panel sounds good for this election. Don't want to make massive changes now.

Over the summer, we might rip that code out. Can always be reverted by whomever is in charge in the future.

**Comment by draab** [comment]
Yeah a toggle to hide the from the site would be fine.

**Comment by draab** [comment]
Flag has been added to the site to enabled/disable parties based on what the rules of that particular election are.
