### ISSUE TITLE
Offices with multiple openings should indicate so on the offices page

### ISSUE THREAD

**Issue by justetz** [wtg/elections#74]
For offices that have more than one opening, the listing on the offices page should indicate so. Some students have felt discouraged from running for a senator race because they see multiple students running and see it as a saturated race, when in actuality there are still less candidates than number of openings.

I've included what I'm envisioning here:

<img width="521" alt="screen shot 2017-03-02 at 1 10 15 pm" src="https://cloud.githubusercontent.com/assets/1284928/23520630/dbb261fc-ff49-11e6-9c02-c79f4035194b.png">

I can submit a pull-request with this minor HTML tweak.

**Comment by kochman** [comment]
Great idea. We can review a pull request and get that merged in if it looks good.
