### ISSUE TITLE
Per-candidate nominations view

### ISSUE THREAD

**Issue by kochman** [wtg/elections#77]
This would show all nominations recorded for any candidate.

It would also show invalid nominations (which aren't currently recorded). This would help RnE figure out why they're invalid and make it easier to re-enter them if it turns out that they should be accepted.

**Comment by draab** [comment]
This especially helpful as RnE has moved away from marking elections forms since members of the group don't ever see the paper copies. They are scanned by the Union Admin Office and the originals are kept in a binder kept by the Chairman in the RnE closet.

**Comment by justetz** [comment]
I have some free time this afternoon and will give it a shot in a separate branch!

**Comment by kochman** [comment]
This is partially done in fd2167a. Recorded nominations are displayed.

Next up is to record invalid nominations and show them.

**Comment by kochman** [comment]
Resolved in 31d32c7.
